server:
  port: ${PORT:8083}

spring:
  application.name: merchant-service # cambia segÃºn el MS
  boot:
    admin:
      client:
        url: https://admin-server-production-a57e.up.railway.app/
        username: admin                       # ðŸ‘ˆ usuario del Admin
        password: ${ADMIN_PWD:SuperSeguro123}
        instance:
          management-base-url: http://${RAILWAY_PRIVATE_DOMAIN}:${PORT:8083}
          service-base-url: http://${RAILWAY_PRIVATE_DOMAIN}:${PORT:8083}

datasource:
  url: ${JDBC_URL:jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 10000
    pool-name: MerchantHikariPool

  r2dbc:
    # igual idea con R2DBC_URL
    url: ${R2DBC_URL:r2dbc:postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false

  flyway:
    enabled: true
    url: ${JDBC_URL:jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:localhost}}
    prefer-ip-address: false
    non-secure-port: ${PORT:${server.port:8083}}
    secure-port-enabled: false
    instance-id: "${spring.application.name}:${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:${HOSTNAME}}}:${PORT:${server.port:8083}}"
    home-page-url: http://${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:${HOSTNAME}}}:${PORT:${server.port:8083}}/
    status-page-url: http://${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:${HOSTNAME}}}:${PORT:${server.port:8083}}/actuator/info
    health-check-url: http://${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:${HOSTNAME}}}:${PORT:${server.port:8083}}/actuator/health
    metadata-map:
      management.port: ${MANAGEMENT_SERVER_PORT:${PORT:${server.port:8083}}}
      management.context-path: ${management.endpoints.web.base-path:/actuator}
management:
  endpoints:
    web:
      exposure:
        include: "*"
