server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: actuator-merchant
          uri: lb://merchant-service
          predicates:
            - Path=/actuator/merchant/**
          filters:
            - StripPrefix=2
        - id: auth-route
          uri: lb://AUTH-MS-JAVA
          predicates:
            - Path=/actuator/auth/**
          filters:
            - StripPrefix=2
        - id: auth-route
          uri: lb://AUTH-MS-JAVA
          predicates:
            - Path=/auth/login
            - Method=POST
          filters:
            - StripPrefix=0
        - id: auth-route
          uri: lb://AUTH-MS-JAVA
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:localhost}}
    prefer-ip-address: false
    non-secure-port: ${PORT:${server.port:8080}}
    secure-port-enabled: false
    instance-id: "${spring.application.name}:${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:${HOSTNAME}}}:${PORT:${server.port:8080}}"
    home-page-url: http://${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:${HOSTNAME}}}:${PORT:${server.port:8080}}/
    status-page-url: http://${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:${HOSTNAME}}}:${PORT:${server.port:8080}}/actuator/info
    health-check-url: http://${EUREKA_INSTANCE_HOST:${RAILWAY_PRIVATE_DOMAIN:${HOSTNAME}}}:${PORT:${server.port:8080}}/actuator/health
    metadata-map:
      management.port: ${MANAGEMENT_SERVER_PORT:${PORT:${server.port:8080}}}
      management.context-path: ${management.endpoints.web.base-path:/actuator}
management:
  endpoints:
    web:
      exposure:
        include: "*"
