server:
  port: ${PORT:8081}

spring:
  application.name: auth-ms-java  # cambia segÃºn el MS
  boot:
    admin:
      client:
        url: https://admin-server-production-a57e.up.railway.app/
        username: admin                       # ðŸ‘ˆ usuario del Admin
        password: ${ADMIN_PWD:SuperSeguro123}
        instance:
          management-base-url: http://${RAILWAY_PRIVATE_DOMAIN}:${PORT:8081}
          service-base-url: http://${RAILWAY_PRIVATE_DOMAIN}:${PORT:8081}

auth:
  issuer: ${AUTH_ISSUER:https://auth.payflex.local}
  audience: ${AUTH_AUDIENCE:payflex-apis}
  access-token-ttl-minutes: ${ACCESS_TOKEN_TTL_MINUTES:10}
  refresh-token-ttl-days: ${REFRESH_TOKEN_TTL_DAYS:30}
  cookie:
    name: ${COOKIE_NAME:session}
    domain: ${COOKIE_DOMAIN:localhost}
    secure: ${COOKIE_SECURE:true}
    sameSite: ${COOKIE_SAMESITE:Lax}
    httpOnly: ${COOKIE_HTTP_ONLY:true}

pocketbase:
  url: ${POCKETBASE_URL:http://localhost:8090}
  collection: ${POCKETBASE_COLLECTION:users}
  merchantField: ${POCKETBASE_MERCHANT_FIELD:merchantId}
  rolesField: ${POCKETBASE_ROLES_FIELD:roles}
  timeout:
    connect: 5000
    read: 15000
    write: 15000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS
