server:
  port: ${PORT:8081}

spring:
  application.name: auth-ms-java  # cambia segÃºn el MS
  boot:
    admin:
      client:
        url: https://admin-server-production-a57e.up.railway.app/
        username: admin                       # ðŸ‘ˆ usuario del Admin
        password: ${ADMIN_PWD:SuperSeguro123}
        instance:
          # URL privada (para que el admin acceda al Actuator)
          management-base-url: http://${RAILWAY_PRIVATE_DOMAIN}:${PORT:8081}
          service-base-url: http://${RAILWAY_PRIVATE_DOMAIN}:${PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS
