server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 30000
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
